version: '3.8'

services:
  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: backend
    volumes:
      - ./backend:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`yourdomain.com`)"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
    networks:
      - web

  frontend:
    build: ./frontend
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yourdomain.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - web

  turnserver:
    image: instrumentisto/turnserver
    container_name: turnserver
    ports:
      - "3478:3478"
      - "49152-65535:49152-65535"
    volumes:
      - ./turnserver/turnserver.conf:/etc/turnserver/turnserver.conf
      - ./turnserver/turnserver.crt:/etc/turnserver/turnserver.crt
      - ./turnserver/turnserver.key:/etc/turnserver/turnserver.key
    environment:
      - TURN_SERVER_REALM=yourdomain.com
      - TURN_SERVER_USER=testuser
      - TURN_SERVER_PASSWORD=testpassword
    networks:
      - web

  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"                           # Включение панели управления Traefik
      - "--providers.docker=true"                       # Включение Docker провайдера
      - "--entrypoints.web.address=:80"                 # HTTP точка входа
      - "--entrypoints.websecure.address=:443"          # HTTPS точка входа
      - "--certificatesresolvers.http.acme.httpchallenge=true"  # Включение ACME HTTP challenge для Let's Encrypt
      - "--certificatesresolvers.http.acme.httpchallenge.entrypoint=web"  # HTTP точка входа для ACME challenge
      - "--certificatesresolvers.http.acme.email=youremail@example.com"   # Email для Let's Encrypt
      - "--certificatesresolvers.http.acme.storage=/letsencrypt/acme.json"  # Хранилище сертификатов
    ports:
      - "80:80"                  # HTTP порт
      - "443:443"                # HTTPS порт
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Docker сокет для Traefik
      - "./letsencrypt:/letsencrypt"                  # Объем для сертификатов Let's Encrypt
    networks:
      - web

networks:
  web:
    external: true
